### ISSUE TITLE
step 2 suggestion

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/blockscad-pendant#10]
Hi!
When talking about the design being centred, should it read "Cylinders are automatically centred along the X, Y, and Z axes" rather than "Cylinders are automatically centred along the X and Y axes"?
Thanks!

**Comment by tracygardner** [comment]
@jennirpf This might seem a little odd, but when you say 'not centered' the default, then cylinders are still centred along X and Y but sit on the surface. If you choose 'centered' (which this project does not) then they are also centred along the Z axis.

**Comment by jennirpf** [comment]
@tracygardner That is what I thought, thank you for clarifying! It currently reads as follows:
"Cylinders are automatically centred along the X and Y axes. Select not centered so that the pendant sits on the surface. (This means that the Z axis value is larger than 0)."
I wondered if in the first instance, it should say X, Y, and Z axes, so that it is clear that if the learner were to select "centered", the cylinders would be centred along the Z axis too. Sorry if that doesn't make any sense!

**Comment by tracygardner** [comment]
@jennirpf Perhaps it should say 'Make sure not centred is selected'. (It's the default which might be what's confusing you?)

The first point is that cylinders are always centred along then X and Y axes whichever option you choose. 
If you choose not centered (the default) which we do in this case then the shape will sit on the surface.
If you instead change the drop down to centered (not the default) then it will also be centered along the Z axis. 

(Cubes are not centered around X, Y or Z if you choose not centered!)

**Comment by jennirpf** [comment]
Ok, great, thank you! In that case, I think it is fine as it is. 
Thanks again!
